### ISSUE TITLE
MINOR: Add validation to the get_resource_config method in GrpcPlacementService

### ISSUE THREAD

**Issue by Pikady** [robustmq/robustmq#542]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Add validation to the get_resource_configmethod in GrpcPlacementService and fill in the test case. 

Tips:
you can implement the `ValidateExt` trait on `GetResourceConfigRequest`, then invoke ` validate_ext ` function to achieve the validation functionality.

- you can locate the ValidateExt trait in the file: src\placement-center\src\server\grpc\validate.rs
- you need to add validation to the node_list method in this file:  src\placement-center\src\server\grpc\service_placement.rs
- you need to fill in the test case in this file: src\grpc-clients\tests\placement_test.rs

reference:
- https://github.com/robustmq/robustmq/pull/548)https://github.com/robustmq/robustmq/pull/548

**Comment by KevinUW114514** [comment]
mark
