### ISSUE TITLE
MINOR:  Add validation to the set_idempotent_data method in GrpcPlacementService and fill in the test case

### ISSUE THREAD

**Issue by Pikady** [robustmq/robustmq#545]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Add validation to the set_idempotent_data method in GrpcPlacementService and fill in the test case. 

Tips:

You can implement the `ValidateExt` trait on `SetIdempotentDataRequest`, then invoke ` validate_ext ` function to achieve the validation functionality.

- you can locate the ValidateExt trait in the file: src\placement-center\src\server\grpc\validate.rs
- you need to add validation to the set_idempotent_data method in this file:  src\placement-center\src\server\grpc\service_placement.rs
- you need to fill in the test case in this file: src\grpc-clients\tests\placement_test.rs

references:
- https://github.com/robustmq/robustmq/pull/548)https://github.com/robustmq/robustmq/pull/548

**Comment by PorterZhang2021** [comment]
please assign me.thanks.
