### ISSUE TITLE
MINOR:  Add validation to the delete_idempotent_data method in GrpcPlacementService and fill in the test case

### ISSUE THREAD

**Issue by Pikady** [robustmq/robustmq#547]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Add validation to the delete_idempotent_data method in GrpcPlacementService and fill in the test case. 

Tips:

You can implement the `ValidateExt` trait on `DeleteIdempotentDataRequest`, then invoke ` validate_ext ` function to achieve the validation functionality.

- you can locate the ValidateExt trait in the file: src\placement-center\src\server\grpc\validate.rs
- you need to add validation to the delete_idempotent_data  method in this file:  src\placement-center\src\server\grpc\service_placement.rs
- you need to fill in the test case in this file: src\grpc-clients\tests\placement_test.rs

references:
- [#526](https://github.com/robustmq/robustmq/pull/526)  
- [#509](https://github.com/robustmq/robustmq/issues/509)

**Comment by Pikady** [comment]
@soumyasen1809 Yes, you can definitely work on this issue. Looking forward for your PR. Happy coding!

**Comment by socutes** [comment]
> Hi @Pikady I am new to Rust and would like to take a shot at this item. Is it possible to work on this item?

Welcome @soumyasen1809

**Comment by soumyasen1809** [comment]
@socutes @Pikady 
please find the PR https://github.com/robustmq/robustmq/pull/561 related to this
