### ISSUE TITLE
COMMAND: MQTT Command supports viewing a list of mqtt topics.

### ISSUE THREAD

**Issue by socutes** [robustmq/robustmq#622]
### What problem does the new feature solve?

[MQTT Command supports viewing a list of mqtt topics.](https://docs.emqx.com/zh/enterprise/v5.8/admin/api-docs.html#tag/Topics/paths/~1topics~1%7Btopic%7D/get)

### What does the feature do?

MQTT Command supports viewing a list of mqtt topics.

**Comment by KevinUW114514** [comment]
mark
