### ISSUE TITLE
websocket 连接发送json数据出现错误ERROR Websocket failed to parse MQTT protocol packet with error message :InsufficientBytes(115)

### ISSUE THREAD

**Issue by who123456789** [robustmq/robustmq#648]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode, Other

### Minimal reproduce step

使用MQTTX客户端通过websocket连接发送json数据导致服务端出错

### What did you expect to see?

无

### What did you see instead?

无

### What operating system did you use?

debian10

**Comment by socutes** [comment]
Thanks @who123456789

**Comment by socutes** [comment]
The test cases with sub/pub json format data of ws and wss did not reproduce the problem.
